Invalid metric perfevent.hwcounters.FP_ARITH_SCALAR_SINGLE.value (PM_ERR_NAME Unknown metric name).
With 10 metrics
exist: True name: poseidon twin_id: ae7487a6-0960-41fb-9c8d-1fddf04df33a collection_id: 639bce466bf01c0dc18e1537 args[0]: 10.92.55.4
in query_twin_state: name:  poseidon
Found db..
SuperTwin is reconstructed from db..
pids: {'pmproxy': '2076', 'pmie': '2658', 'pmcd': '710454', 'pmdaproc': '710459', 'pmdalinux': '710461', 'pmdalmsensors': '710463', 'pmdaperfevent': '717951'}
pids: {'pmproxy': '002076', 'pmie': '002658', 'pmcd': '710454', 'pmdaproc': '710459', 'pmdalinux': '710461', 'pmdalmsensors': '710463', 'pmdaperfevent': '717951'}
METRICS: ['UNHALTED_CORE_CYCLES', 'UNHALTED_REFERENCE_CYCLES', 'INSTRUCTION_RETIRED', 'L1D:REPLACEMENT', 'MEM_UOPS_RETIRED:ALL_LOADS', 'MEM_UOPS_RETIRED:ALL_STORES', 'MEM_LOAD_RETIRED:L1_HIT', 'MEM_LOAD_RETIRED:L2_HIT', 'FP_ARITH:SCALAR_SINGLE', 'FP_ARITH:SCALAR_DOUBLE']
Generated new perfevent pmda configuration..
Executing command on poseidon : mkdir /tmp/dt_files
Executing command on poseidon : sudo sh /tmp/dt_files/reconfigure_perf.sh
Reconfigured remote perfevent pmda
Twin state is registered to db..
pids: {'pmproxy': '2076', 'pmie': '2658', 'pmcd': '710454', 'pmdaproc': '710459', 'pmdalinux': '710461', 'pmdalmsensors': '710463', 'pmdaperfevent': '758795'}
pids: {'pmproxy': '002076', 'pmie': '002658', 'pmcd': '710454', 'pmdaproc': '710459', 'pmdalinux': '710461', 'pmdalmsensors': '710463', 'pmdaperfevent': '758795'}
Interval: 1
Traceback (most recent call last):
  File "overhead_measurements_poseidon.py", line 346, in <module>
    main("10.92.55.4", " -c overhead_configs/poseidon_10.conf :configured", "poseidon", "try0", "poseidon10")
  File "overhead_measurements_poseidon.py", line 254, in main
    _runs["1"], _gots["1"], _ios["1"], _nets["1"] = one_run_two_returns(client, "1", metric1, metric2, fields, sampler_config, duration, name)
  File "overhead_measurements_poseidon.py", line 119, in one_run_two_returns
    time.sleep(duration)
KeyboardInterrupt
